export const ADD_ARTICLE = "ADD_ARTICLE";
export const RESET_ARTICLES = "RESET_ARTICLES";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const EDIT_STORE = "EDIT_STORE";
export const EDIT_ARTICLE = "EDIT_ARTICLE";